### PR TITLE
Update to new DModel API: ekn_id -> id

### PR DESCRIPTION
**Pull request by ptomato**
This also changes the API of the Results return value in the content
metadata provider interface.

https://phabricator.endlessm.com/T22103

### CODE REVIEW

**Comment by ptomato** [comment]
@smspillaz FYI, this changes one of the keys of the `Results()` return value in the content metadata interface.

**Comment by smspillaz** [comment]
> @smspillaz FYI, this changes one of the keys of the Results() return value in the content metadata interface.

Ah okay, thanks for the heads up.

Unfortunately, we can't change the property name in the variant passed through the d-bus interface since that would break compatibility with existing callers who don't have any way of knowing what the new property name is. So we should probably keep it as `ekn_id` there (unless we want to bump the interface version).

**Comment by smspillaz** [comment]
> Unfortunately, we can't change the property name in the variant passed through the d-bus interface 

(I would, however, make a small exception for `ArticleMetadata` considering that we had to revert taht change in the companion app side :/ )

**Comment by ptomato** [comment]
There aren't any existing callers, since it hasn't been released yet! That's why I'd like to get this in ASAP before we branch :smile:

**Comment by smspillaz** [comment]
> There aren't any existing callers, since it hasn't been released yet! That's why I'd like to get this in ASAP before we branch 😄

There are existing callers for the Discovery Feed and Search Provider interfaces (none for ArticleMetadata though).

Like I said, if we want to, we can bump the version encoded in the interface names if we want to change it. But that would require the search provider to also support the old interface to avoid breaking shell search and discovery feed for new apps.

**Comment by ptomato** [comment]
Oh, I do see where this changes the discovery feed interface now. I'll revise it on Monday so that remains unchanged. I don't think it changes the search provider interface.

**Pull request merged**
